package com.orderflow.common.error;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    INVALID_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    CONFLICT,
    INSUFFICIENT_INVENTORY,
    PAYMENT_FAILED,
    ORDER_NOT_CANCELLABLE,
    DUPLICATE_REQUEST,
    RATE_LIMIT_EXCEEDED,
    SIMULATED_PAYMENT_TIMEOUT
}
